spring:
    # 环境 home|cgnb|pro
    profiles:
      active: home
    boot:
      admin:
        client:
          prefer-ip: true
        url: http://localhost:8089/ # 向服务端注册的地址
    aop:
      auto: true
    # jackson时间格式化
    jackson:
        time-zone: GMT+8
        date-format: yyyy-MM-dd HH:mm:ss
    http:
        converters:
          preferred-json-mapper: fastjson
        multipart:
            max-file-size: 100MB
            max-request-size: 100MB
            enabled: true
    #jpa
    jpa:
         hibernate:
           ddl-auto: update
         show-sql: true
#log4j2
logging:
    #config: classpath:/logback-spring.xml
    level:
        org:
            springframework:
                              web:
                                   servlet:
                                        DispatcherServlet: DEBUG
#security
management:
  port: 8086
  security:
     enabled: false

# Mybatis配置
mybatis:
    type-aliases-package: com.terry.gakkisimle.wechat.entity.po.spider
    mapper-locations: classpath:mapper/*.xml

mapper:
    #mappers: com.terry.gakkisimle.im.mapper
    not-empty: false
    identity: MYSQL

pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql

#tomcat参数
server:
    tomcat:
        uri-encoding: UTF-8
        max-threads: 100
        min-spare-threads: 10
    port: 8086
    servlet-path: /

#系统变量配置
sys:
    const:
          webserviceUrl: http://182.151.197.163:9011/thirdparty/webservices/sfjrService?wsdl
          webserviceUsername: frse
          webservicePassword: 123456

    useRedisCache: 1 #是否使用redis缓存
    expireTime: 1800000 #Session过期时间，单位毫秒
    wechatAppSecret: e0177bc4044c4fa29e7b85a4e2da852b
    database: 123456
#优雅关机
endpoints:
  shutdown:
    enabled: true
    sensitive: false