spring:
    # 环境 dev|test|pro
    boot:
      admin:
        client:
          prefer-ip: true
        url: http://localhost:8089/ # 向服务端注册的地址
    aop:
      auto: true
    # jackson时间格式化
    jackson:
        time-zone: GMT+8
        date-format: yyyy-MM-dd HH:mm:ss
    http:
        converters:
          preferred-json-mapper: fastjson
        multipart:
            max-file-size: 100MB
            max-request-size: 100MB
            enabled: true
  #数据源
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driverClassName: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/gakkisimle?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&&characterSetServer=utf8mb4
        username: root
        password: 297234
        initial-size: 5
        max-active: 10
        min-idle: 5
        max-wait: 60000
        pool-prepared-statements: true
        max-pool-prepared-statement-per-connection-size: 20
        time-between-eviction-runs-millis: 60000
        min-evictable-idle-time-millis: 300000
        validation-query: SELECT 1 FROM DUAL
        test-while-idle: true
        test-on-borrow: false
        test-on-return: false
        stat-view-servlet:
            enabled: true
            url-pattern: /druid/*
            login-username: admin
            login-password: 123456
        filter:
            stat:
                log-slow-sql: true
                slow-sql-millis: 1000
                merge-sql: true
            wall:
                config:
                    multi-statement-allow: true
    zipkin:
      base-url: http://localhost:8090
    sleuth:
      sampler:
        percentage: 1.0
    #kafka
    kafka:
      bootstrap-servers: localhost:9092
      producer:
        batch-size: 16384
        buffer-memory: 33554432
        #key-serializer: org.apache.kafka.common.serialization.StringDeserializer
        #value-serializer: org.apache.kafka.common.serialization.StringDeserializer
      consumer:
        group-id: test
        auto-offset-reset: earliest
        enable-auto-commit: true
        auto-commit-interval: 100
        bootstrap-servers: localhost:9092
        concurrency: 10
        zookeeper:
          connect: localhost:2181
        #key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
        #value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#sleuth&&log4j2
logging:
    #config: classpath:/logback-spring.xml
    level:
        org:
            springframework:
                              web:
                                   servlet:
                                        DispatcherServlet: DEBUG
#security
management:
  port: 8086
  security:
     enabled: false

# Mybatis配置
mybatis:
    type-aliases-package: com.terry.gakkisimle.wechat.entity.po.spider
    mapper-locations: classpath:mapper/*.xml

mapper:
    mappers: com.terry.gakkisimle.IM.mapper
    not-empty: false
    identity: MYSQL

pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql

#tomcat参数
server:
    tomcat:
        uri-encoding: UTF-8
        max-threads: 1000
        min-spare-threads: 30
    port: 8086
    servlet-path: /gakkisimle

#系统变量配置
sys:
    const:
          webserviceUrl: http://182.151.197.163:9011/thirdparty/webservices/sfjrService?wsdl
          webserviceUsername: frse
          webservicePassword: 123456

    useRedisCache: 1 #是否使用redis缓存
    expireTime: 1800000 #Session过期时间，单位毫秒
    wechatAppSecret: e0177bc4044c4fa29e7b85a4e2da852b
    database: 123456
#优雅关机
endpoints:
  shutdown:
    enabled: true
    sensitive: false